In [2]:
import psycopg
import pandas as pd
import numpy as np
import math as m

In [3]:
conn = psycopg.connect(
    host = "sculptor.stat.cmu.edu", dbname = "hireng",
    user = "hireng", password = "aiVee0Ohs"
)

cur = conn.cursor()
df = pd.read_csv('./HHS_data/2022-09-23-hhs-data.csv')

conn.autocommit = True
df = df.replace({np.nan: None})

In [173]:
# df["all_adult_hospital_beds_7_day_avg"] = df["all_adult_hospital_beds_7_day_avg"].astype(float)
# df["all_pediatric_inpatient_beds_7_day_avg"] = df["all_pediatric_inpatient_beds_7_day_avg"].astype(float)
# df["all_adult_hospital_inpatient_bed_occupied_7_day_coverage"] = df["all_adult_hospital_inpatient_bed_occupied_7_day_coverage"].astype(float)
# df["all_pediatric_inpatient_bed_occupied_7_day_avg"] = df["all_pediatric_inpatient_bed_occupied_7_day_avg"].astype(float)
# df["total_icu_beds_7_day_avg"] = df["total_icu_beds_7_day_avg"].astype(float)
# df["icu_beds_used_7_day_avg"] = df["icu_beds_used_7_day_avg"].astype(float)
# df["inpatient_beds_used_covid_7_day_avg"] = df["inpatient_beds_used_covid_7_day_avg"].astype(float)
# df["staffed_icu_adult_patients_confirmed_covid_7_day_avg"] = df["staffed_icu_adult_patients_confirmed_covid_7_day_avg"].astype(float)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4996 entries, 0 to 4995
Columns: 127 entries, hospital_pk to total_staffed_pediatric_icu_beds_7_day_sum
dtypes: bool(1), int64(39), object(87)
memory usage: 4.8+ MB

In [16]:
df2=pd.DataFrame(columns = ["hospital_pk", "collection_week", "all_adult_hospital_beds_7_day_avg", "all_pediatric_inpatient_beds_7_day_avg", "all_adult_hospital_inpatient_bed_occupied_7_day_coverage", "all_pediatric_inpatient_bed_occupied_7_day_avg", "total_icu_beds_7_day_avg", "icu_beds_used_7_day_avg", "inpatient_beds_used_covid_7_day_avg", "staffed_icu_adult_patients_confirmed_covid_7_day_avg"])
n_row=0
df2

Empty DataFrame
Columns: [hospital_pk, collection_week, all_adult_hospital_beds_7_day_avg, all_pediatric_inpatient_beds_7_day_avg, all_adult_hospital_inpatient_bed_occupied_7_day_coverage, all_pediatric_inpatient_bed_occupied_7_day_avg, total_icu_beds_7_day_avg, icu_beds_used_7_day_avg, inpatient_beds_used_covid_7_day_avg, staffed_icu_adult_patients_confirmed_covid_7_day_avg]
Index: []

In [179]:
# a = df.iloc[0, 96]
# print(m.isnan(a))
# print(type(a))
# a = (str(a)).find("(")
# print(a)

# b = df.iloc[1, 96][6:].strip("()").split(" ")[0]
# print(b)
# print(type(b))

# c = float(df.iloc[2, 96][6:].strip("()").split(" ")[0])
# print(c)
# print(type(c))

# if (m.isnan(df.iloc[0, 96])):
#     print("Yes")

d = df.iloc[0, 0]
print(d)

640001

In [5]:
with conn.transaction():
    for row in range(df.shape[0]):
        hospital_pk = df.iloc[row, 0]
        state = df.iloc[row, 2]
        hospital_name = df.iloc[row, 4]
        address = df.iloc[row, 5]
        city = df.iloc[row, 6]
        zip = df.iloc[row, 7]
        fips_code = df.iloc[row, 9]
        geocoded_hospital_address = (df.iloc[row, 96])
        if (((geocoded_hospital_address is None))):
            geocoded_hospital_address_1 = None
            geocoded_hospital_address_2 = None
        else:
            geocoded_hospital_address_1 =  float(geocoded_hospital_address[6:].strip("()").split(" ")[0])
            geocoded_hospital_address_2 =  float(geocoded_hospital_address[6:].strip("()").split(" ")[1])
        cur.execute("insert into hospital_inf (hospital_pk, state, hospital_name, address, city, zip, fips_code, geocoded_hospital_address_1, geocoded_hospital_address_2) values (%s, %s, %s, %s, %s, %s, %s, %s, %s) ON CONFLICT (hospital_pk) DO NOTHING ", (hospital_pk, state, hospital_name, address, city, int(zip), (fips_code), (geocoded_hospital_address_1), (geocoded_hospital_address_2)))
        #address, city, zip, fips_code, geocoded_hospital_address) values (%s, %s, %s, %s, %s, %s, %s, %s)" "ON CONFLICT (hospital_pk) DO NOTHING ", (hospital_pk, state, hospital_name, address, city, zip, fips_code, geocoded_hospital_address))

In [11]:
df = df.replace({np.nan: None})
missing_values = [-999999,np.nan]
df=pd.read_csv("HHS_data/2022-09-23-hhs-data.csv", na_values=missing_values)

In [14]:
def if_float(n):
    if (m.isnan(n)):
        return None
    else:
        return float(n)

In [15]:
nrow=0
df3=pd.DataFrame(columns=["hospital_pk", "collection_week", "all_adult_hospital_beds_7_day_avg", "all_pediatric_inpatient_beds_7_day_avg", "all_adult_hospital_inpatient_bed_occupied_7_day_coverage", "all_pediatric_inpatient_bed_occupied_7_day_avg", "total_icu_beds_7_day_avg", "icu_beds_used_7_day_avg", "inpatient_beds_used_covid_7_day_avg", "staffed_icu_adult_patients_confirmed_covid_7_day_avg"])
num_rows_inserted_weekly=0
with conn.transaction():
    for row in range(df.shape[0]):
        hospital_pk = df.iloc[row, 0]
        collection_week = df.iloc[row, 1]
        all_adult_hospital_beds_7_day_avg = df.iloc[row, 12]
        all_pediatric_inpatient_beds_7_day_avg = df.iloc[row, 111]
        all_adult_hospital_inpatient_bed_occupied_7_day_coverage = df.iloc[row, 55]
        all_pediatric_inpatient_bed_occupied_7_day_avg = df.iloc[row, 108]
        total_icu_beds_7_day_avg = df.iloc[row, 22]
        icu_beds_used_7_day_avg = df.iloc[row, 24]
        inpatient_beds_used_covid_7_day_avg = df.iloc[row, 16]
        staffed_icu_adult_patients_confirmed_covid_7_day_avg = df.iloc[row, 27]
        try:
            with conn.transaction():
                cur.execute("insert into hospital_weeekly(hospital_pk, collection_week, all_adult_hospital_beds_7_day_avg, all_pediatric_inpatient_beds_7_day_avg, all_adult_hospital_inpatient_bed_occupied_7_day_coverage, all_pediatric_inpatient_bed_occupied_7_day_avg, total_icu_beds_7_day_avg, icu_beds_used_7_day_avg, inpatient_beds_used_covid_7_day_avg, staffed_icu_adult_patients_confirmed_covid_7_day_avg) " 
                "values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (hospital_pk, collection_week, if_float(all_adult_hospital_beds_7_day_avg), if_float(all_pediatric_inpatient_beds_7_day_avg), if_float(all_adult_hospital_inpatient_bed_occupied_7_day_coverage), if_float(all_pediatric_inpatient_bed_occupied_7_day_avg), if_float(total_icu_beds_7_day_avg), if_float(icu_beds_used_7_day_avg), if_float(inpatient_beds_used_covid_7_day_avg), if_float(staffed_icu_adult_patients_confirmed_covid_7_day_avg)))
        except Exception as e:
            # if ((all_adult_hospital_beds_7_day_avg < 0) or (all_adult_hospital_beds_7_day_avg == None)):
            #     print("all_adult_hospital_beds_7_day_avg failed")
            # elif (all_pediatric_inpatient_beds_7_day_avg < 0 or (all_pediatric_inpatient_beds_7_day_avg == None)):
            #     print("all_pediatric_inpatient_beds_7_day_avg failed")
            # elif (all_adult_hospital_inpatient_bed_occupied_7_day_coverage < 0 or (all_adult_hospital_inpatient_bed_occupied_7_day_coverage == None)):
            #     print("all_pediatric_inpatient_beds_7_day_avg failed")
            # elif (all_pediatric_inpatient_bed_occupied_7_day_avg < 0 or (all_pediatric_inpatient_bed_occupied_7_day_avg == None)):
            #     print("all_pediatric_inpatient_bed_occupied_7_day_avg")
            # elif (total_icu_beds_7_day_avg < 0) or (total_icu_beds_7_day_avg == None):
            #     print("total_icu_beds_7_day_avg")
            # elif (icu_beds_used_7_day_avg < 0) or (icu_beds_used_7_day_avg == None):
            #     print("icu_beds_used_7_day_avg")
            # elif (inpatient_beds_used_covid_7_day_avg <0) or (inpatient_beds_used_covid_7_day_avg == None):
            #     print("inpatient_beds_used_covid_7_day_avg")
            # else:
            #     print("staffed_icu_adult_patients_confirmed_covid_7_day_avg")
            print("Insert failed!", e)
            df3.loc[nrow]=df.iloc[row,[0,1,12,111,55,108,22,24,16,27]]
            nrow+=1
        else:
            num_rows_inserted_weekly += 1

print(nrow)
print(num_rows_inserted_weekly)

Insert failed! new row for relation "hospital_weeekly" violates check constraint "hospital_weeekly_all_pediatric_inpatient_beds_7_day_avg_check"
DETAIL:  Failing row contains (1028, 111337, 2022-09-23, 30, -1, 7, 0, 0, 0, 0, 0).
1
4995

In [41]:
qf=pd.read_csv("CMS_data/Hospital_General_Information-2021-07.csv")
(qf.head(10))

,Facility ID,Facility Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,Houston,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,1,9,1,NaN,8,8,NaN,14,11,NaN
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,Marshall,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,9,1,NaN,8,8,NaN,14,14,NaN
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,Lauderdale,(256) 768-8400,Acute Care Hospitals,Proprietary,...,1,7,1,NaN,8,8,NaN,14,11,NaN
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,Covington,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,6,0,NaN,8,8,NaN,14,7,NaN
4,010008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,Crenshaw,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,4,0,NaN,8,Not Available,5.0,14,8,NaN
5,010011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,Jefferson,(205) 838-3122,Acute Care Hospitals,Voluntary non-profit - Private,...,0,6,3,NaN,8,8,NaN,14,9,NaN
6,010012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DeKalb,(256) 845-3150,Acute Care Hospitals,Proprietary,...,0,7,0,NaN,8,8,NaN,14,10,NaN
7,010016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,Shelby,(205) 620-8100,Acute Care Hospitals,Voluntary non-profit - Private,...,1,7,1,NaN,8,8,NaN,14,10,NaN
8,010018,CALLAHAN EYE HOSPITAL,"1720 UNIVERSITY BLVD, SUITE 500",BIRMINGHAM,AL,35233,Jefferson,(205) 325-8100,Acute Care Hospitals,Voluntary non-profit - Private,...,0,1,0,NaN,8,Not Available,5.0,14,3,NaN
9,010019,HELEN KELLER HOSPITAL,1300 SOUTH MONTGOMERY AVENUE,SHEFFIELD,AL,35660,Colbert,(256) 386-4556,Acute Care Hospitals,Government - Hospital District or Authority,...,0,9,0,NaN,8,8,NaN,14,12,NaN

In [42]:
missing_values = [-999999, np.nan]
qf=pd.read_csv("CMS_data/Hospital_General_Information-2021-07.csv", na_values=missing_values)
qf.head(10)
# qf.loc[qf["Hospital overall rating"]== "Not Available"]=np.nan
# qf["Hospital overall rating"]
# qf["Hospital overall rating"].dtype

,Facility ID,Facility Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,Houston,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,1,9,1,NaN,8,8,NaN,14,11,NaN
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,Marshall,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,9,1,NaN,8,8,NaN,14,14,NaN
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,Lauderdale,(256) 768-8400,Acute Care Hospitals,Proprietary,...,1,7,1,NaN,8,8,NaN,14,11,NaN
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,Covington,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,6,0,NaN,8,8,NaN,14,7,NaN
4,010008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,Crenshaw,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,4,0,NaN,8,Not Available,5.0,14,8,NaN
5,010011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,Jefferson,(205) 838-3122,Acute Care Hospitals,Voluntary non-profit - Private,...,0,6,3,NaN,8,8,NaN,14,9,NaN
6,010012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DeKalb,(256) 845-3150,Acute Care Hospitals,Proprietary,...,0,7,0,NaN,8,8,NaN,14,10,NaN
7,010016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,Shelby,(205) 620-8100,Acute Care Hospitals,Voluntary non-profit - Private,...,1,7,1,NaN,8,8,NaN,14,10,NaN
8,010018,CALLAHAN EYE HOSPITAL,"1720 UNIVERSITY BLVD, SUITE 500",BIRMINGHAM,AL,35233,Jefferson,(205) 325-8100,Acute Care Hospitals,Voluntary non-profit - Private,...,0,1,0,NaN,8,Not Available,5.0,14,3,NaN
9,010019,HELEN KELLER HOSPITAL,1300 SOUTH MONTGOMERY AVENUE,SHEFFIELD,AL,35660,Colbert,(256) 386-4556,Acute Care Hospitals,Government - Hospital District or Authority,...,0,9,0,NaN,8,8,NaN,14,12,NaN

In [43]:
d = qf.iloc[8,0]
print(d)
print(type(d))
e = df.iloc[7,0]
print(e)
print(type(e))
print(qf.head(10))

010018
<class 'str'>
010100
<class 'str'>
  Facility ID                    Facility Name  \
0      010001  SOUTHEAST HEALTH MEDICAL CENTER
1      010005         MARSHALL MEDICAL CENTERS
2      010006     NORTH ALABAMA MEDICAL CENTER
3      010007         MIZELL MEMORIAL HOSPITAL
4      010008      CRENSHAW COMMUNITY HOSPITAL
5      010011               ST. VINCENT'S EAST
6      010012   DEKALB REGIONAL MEDICAL CENTER
7      010016    SHELBY BAPTIST MEDICAL CENTER
8      010018            CALLAHAN EYE HOSPITAL
9      010019            HELEN KELLER HOSPITAL

                           Address        City State  ZIP Code County Name  \
0           1108 ROSS CLARK CIRCLE      DOTHAN    AL     36301     Houston
1       2505 U S HIGHWAY 431 NORTH        BOAZ    AL     35957    Marshall
2              1701 VETERANS DRIVE    FLORENCE    AL     35630  Lauderdale
3                    702 N MAIN ST         OPP    AL     36467   Covington
4              101 HOSPITAL CIRCLE     LUVERNE    AL     36049    Crenshaw
5       50 MEDICAL PARK EAST DRIVE  BIRMINGHAM    AL     35235   Jefferson
6             200 MED CENTER DRIVE  FORT PAYNE    AL     35968      DeKalb
7          1000 FIRST STREET NORTH   ALABASTER    AL     35007      Shelby
8  1720 UNIVERSITY BLVD, SUITE 500  BIRMINGHAM    AL     35233   Jefferson
9     1300 SOUTH MONTGOMERY AVENUE   SHEFFIELD    AL     35660     Colbert

     Phone Number         Hospital Type  \
0  (334) 793-8701  Acute Care Hospitals
1  (256) 593-8310  Acute Care Hospitals
2  (256) 768-8400  Acute Care Hospitals
3  (334) 493-3541  Acute Care Hospitals
4  (334) 335-3374  Acute Care Hospitals
5  (205) 838-3122  Acute Care Hospitals
6  (256) 845-3150  Acute Care Hospitals
7  (205) 620-8100  Acute Care Hospitals
8  (205) 325-8100  Acute Care Hospitals
9  (256) 386-4556  Acute Care Hospitals

                            Hospital Ownership  ...  \
0  Government - Hospital District or Authority  ...
1  Government - Hospital District or Authority  ...
2                                  Proprietary  ...
3               Voluntary non-profit - Private  ...
4                                  Proprietary  ...
5               Voluntary non-profit - Private  ...
6                                  Proprietary  ...
7               Voluntary non-profit - Private  ...
8               Voluntary non-profit - Private  ...
9  Government - Hospital District or Authority  ...

  Count of READM Measures Better Count of READM Measures No Different  \
0                              1                                    9
1                              0                                    9
2                              1                                    7
3                              0                                    6
4                              0                                    4
5                              0                                    6
6                              0                                    7
7                              1                                    7
8                              0                                    1
9                              0                                    9

  Count of READM Measures Worse  READM Group Footnote  \
0                             1                   NaN
1                             1                   NaN
2                             1                   NaN
3                             0                   NaN
4                             0                   NaN
5                             3                   NaN
6                             0                   NaN
7                             1                   NaN
8                             0                   NaN
9                             0                   NaN

  Pt Exp Group Measure Count Count of Facility Pt Exp Measures  \
0                          8                                 8
1                          8                                 8
2                          8                                 8
3                          8                                 8
4                          8                     Not Available
5                          8                                 8
6                          8                                 8
7                          8                                 8
8                          8                     Not Available
9                          8                                 8

  Pt Exp Group Footnote TE Group Measure Count Count of Facility TE Measures  \
0                   NaN                     14                            11
1                   NaN                     14                            14
2                   NaN                     14                            11
3                   NaN                     14                             7
4                   5.0                     14                             8
5                   NaN                     14                             9
6                   NaN                     14                            10
7                   NaN                     14                            10
8                   5.0                     14                             3
9                   NaN                     14                            12

   TE Group Footnote
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
5                NaN
6                NaN
7                NaN
8                NaN
9                NaN

[10 rows x 38 columns]

In [39]:
def if_float_for_str(n):
    if (type(n) ==  str):
        return float(n)
    else:
        return None

In [40]:
a = qf.iloc[5335,12]
b = if_float_for_str(a)
print(a, b)
print(type(a), type(b))

ValueError: could not convert string to float: 'Not Available'

In [29]:
nrow2=0
df6=pd.DataFrame(columns=["hospital_pk, type_of_hospital, ownership, emergency, overall_quality_rating"])
num_rows_inserted_quality=0
with conn.transaction():
    for row in range(qf.shape[0]):
        facility_id = qf.iloc[row, 0]
        time = '2017-03-14'
        type_of_hospital = qf.iloc[row, 8]
        ownership = qf.iloc[row, 9]
        emergency = qf.iloc[row, 10]
        overall_quality_rating = qf.iloc[row, 12]
        try:
            with conn.transaction():
                cur.execute("insert into hospital_qual (facility_id, update_time, type_of_hospital, ownership, emergency, overall_quality_rating) values ( %s, %s, %s, %s, %s, %s)", (facility_id, time, type_of_hospital, ownership, emergency, if_float_for_str(overall_quality_rating)))
        except Exception as e:
            print("Insert failed!", e)
            df6.loc[nrow2]=df.iloc[row,[0,8,9,10,12]]
            nrow2+=1
        else:
            num_rows_inserted_quality += 1

print(nrow2)
print(num_rows_inserted_quality)

0
5336